version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local